### ISSUE TITLE
Mail de confirmation côté utilisateur (celui qui réserve un créneau)

### ISSUE THREAD

**Issue by lcarel** [xebia-france/expert-cafe-android#4]
Mail reçu : 
"Hello MR UTILISATEUR,

Appointment booked from 18h15 to 18H30 with Jeremy V for FRONT,NODE.JS,ANGULAR.JS,WEB

Regards,
Expert Café Team"

On n'a pas le subject de la réservation (surement remplacer le domain par le subject ?)

**Comment by jsmadja** [comment]
Mettre des espaces après les virgules aussi (sauf si c'est tapé à la main ?)

**Comment by lcarel** [comment]
Oui Julien je m'en occupe (car c'est tapé à la main)

**Comment by blacroix** [comment]
Tu peux même retirer les majuscules @krlnr 

C'est bon c'est corrigé, pas la peine de changer l'application Android ça se passe sur Parse.
